GAME_TITLE = "Mau Mau"
WIDTH = 800
HEIGHT = 600
WELLCOME_TEXT = "Wellcome"
IP_ADDRESS = "127.0.0.1"
PORT = "1234"
RESOURCES_PATH = "./resources/"
COMPONENTS_UI_PATH = f'{RESOURCES_PATH}ComponentUi/'
ICON_PATH = f'{RESOURCES_PATH}Icon/icon.png'
CARDS_PATH = f'{RESOURCES_PATH}Cards/'

